### ISSUE TITLE
Create a for you page layout

### ISSUE THREAD

**Issue by nnema05** [nnema05/Team_5_Recitation11_Project#3]
Acceptance criteria: Can swipe left and right on clothes and the ones you swipe right on saves into your saved clothing space

**Comment by soumya9236** [comment]
A user should be able to click a drop down and go to a for you page, where people can explore new clothing

**Comment by soumya9236** [comment]
Acceptance Criteria: When a user clicks on the for you page in the nav bar they should be able to navigate to this page, and see the for you page layout.
