### ISSUE TITLE
create a my closest page

### ISSUE THREAD

**Issue by nnema05** [nnema05/Team_5_Recitation11_Project#4]
Create a page for all the user's closet outfits. They can swipe right and left on it. 
Acceptance Criteria:Can upload outfits. Displays the users outfits that they uploaded, and the option to swipe right and left is available. And whatever you swipe right on saves into your saved clothes

**Comment by soumya9236** [comment]
Create a page for all the user's saved outfits. As a user they should be able to save the outfits that they like for future use as well
